# PaddleOCR manual recovery commands
# Generated by install_paddle_ocr_suite.ps1

# 1. Open the project folder
Set-Location 'F:\Documents\Paddle_OCR'

# 2. Install PaddleOCR / Pillow / PyMuPDF
& { $env:PYTHONNOUSERSITE='1'; $env:PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK='True'; & 'F:\Documents\Paddle_OCR\.venv\Scripts\python.exe' -m pip install --disable-pip-version-check --progress-bar off --timeout 60 --retries 1 --upgrade 'paddleocr' 'pillow' 'pymupdf' }

# 3. Install PP-StructureV3 dependencies
& { $env:PYTHONNOUSERSITE='1'; $env:PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK='True'; & 'F:\Documents\Paddle_OCR\.venv\Scripts\python.exe' -m pip install --disable-pip-version-check --progress-bar off --timeout 60 --retries 1 'paddlex[ocr]==3.4.2' }

# 4. Verify the installed environment
& { $env:PYTHONNOUSERSITE='1'; $env:PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK='True'; & 'F:\Documents\Paddle_OCR\.venv\Scripts\python.exe' -c 'import fitz, paddle, paddleocr; from paddleocr import PaddleOCR; PaddleOCR(use_doc_orientation_classify=False, use_doc_unwarping=False, use_textline_orientation=False, text_rec_score_thresh=0.0); paddle.utils.run_check(); print("OCR_VERIFY_OK")' }

